/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dvi.proyectoTarea.ventanas;

import dvi.proyectoTarea.recursos.dataaccess.DataAccess;
import dvi.proyectoTarea.recursos.objetos.Intent;
import dvi.proyectoTarea.recursos.objetos.Review;
import dvi.proyectoTarea.recursos.objetos.Usuari;
import java.awt.Desktop;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alumne
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        initTables();
        jPanel1.setVisible(false);

    }

    private void initTables() {
        DefaultTableModel dtm1 = new DefaultTableModel();
        dtm1.setColumnIdentifiers(new String[]{"Intent","Usuari", "Exercici","Inici","Estat"});
        intentTable.setModel(dtm1);

        DefaultTableModel dtm2 = new DefaultTableModel();
        dtm2.setColumnIdentifiers(new String[]{"Usuari", "ID"});
        userTable.setModel(dtm2);

        tablasNoEditables();
        cargarUserTable();
        cargarPendingIntentTable();
    }

    private void tablasNoEditables() {
        JTextField tf = new JTextField();
        tf.setEditable(false);
        DefaultCellEditor editor = new DefaultCellEditor(tf);
        intentTable.setDefaultEditor(Object.class, editor);
        userTable.setDefaultEditor(Object.class, editor);

    }

    private void cargarUserTable() {
        DataAccess dataAccess = new DataAccess();
        List<Object[]> userData = dataAccess.getUserData();
        DefaultTableModel dtm = (DefaultTableModel) userTable.getModel();
        dtm.setRowCount(0); // Clear the table before loading new data
        for (Object[] row : userData) {
            dtm.addRow(row);
        }
    }

    private void cargarIntentTablePU(int id) {
        DataAccess dataAccess = new DataAccess();
        ArrayList<Intent> Intents = dataAccess.getAttemptsPerUser(id);
        List<Object[]> IntentData= dataAccess.getIntentData(Intents);
        DefaultTableModel dtm = (DefaultTableModel) intentTable.getModel();
        dtm.setRowCount(0); // Clear the table before loading new data
        for (Object[] row : IntentData) {
            dtm.addRow(row);
        }
        
        pintarTabla();

        if (intentTable.getRowCount() > 0) {
            intentTable.setRowSelectionInterval(0, 0);
        }
    }

    private void cargarIntentTable() {
        DataAccess dataAccess = new DataAccess();
        ArrayList<Intent> Intents = dataAccess.getAttempts();
        List<Object[]> IntentData= dataAccess.getIntentData(Intents);
        DefaultTableModel dtm = (DefaultTableModel) intentTable.getModel();
        dtm.setRowCount(0); // Clear the table before loading new data
        for (Object[] row : IntentData) {
            dtm.addRow(row);
        }
        
        pintarTabla();
        if (intentTable.getRowCount() > 0) {
            intentTable.setRowSelectionInterval(0, 0);
        }
    }

    private void cargarPendingIntentTable() {
        DataAccess dataAccess = new DataAccess();
        ArrayList<Intent> pendingIntent = dataAccess.getAttemptsPendingReview();
        List<Object[]> pendingIntentData= dataAccess.getIntentData(pendingIntent);
        DefaultTableModel dtm = (DefaultTableModel) intentTable.getModel();
        dtm.setRowCount(0); // Clear the table before loading new data
        for (Object[] row : pendingIntentData) {
            dtm.addRow(row);
        }
        
        pintarTabla();
        if (intentTable.getRowCount() > 0) {
            intentTable.setRowSelectionInterval(0, 0);
        }
    }

    private void pintarTabla(){
        
    }

    private void cargarVideo(String ruta) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        Image = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        intentTable = new javax.swing.JTable();
        videoPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        allIntentsButton = new javax.swing.JButton();
        pendingIntentsButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(null);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(new String("https://negrefitnessclub.es/en"));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 680, -1, -1));

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 600, 130, -1));

        Image.setIcon(new javax.swing.ImageIcon("src/main/java/dvi/proyectoTarea/imagenes/logoMinima.png"));
        Image.setAlignmentY(0.0F);
        Image.setFocusable(false);
        jPanel2.add(Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 1200, 780));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1200, 780);

        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        intentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        intentTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        intentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                intentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(intentTable);

        javax.swing.GroupLayout videoPanelLayout = new javax.swing.GroupLayout(videoPanel);
        videoPanel.setLayout(videoPanelLayout);
        videoPanelLayout.setHorizontalGroup(
            videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );
        videoPanelLayout.setVerticalGroup(
            videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        userTable.setFocusable(false);
        userTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(userTable);

        allIntentsButton.setText("Tots");
        allIntentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allIntentsButtonActionPerformed(evt);
            }
        });

        pendingIntentsButton.setText("Pendents");
        pendingIntentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendingIntentsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(videoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(allIntentsButton)
                                .addGap(70, 70, 70)
                                .addComponent(pendingIntentsButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(videoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allIntentsButton)
                    .addComponent(pendingIntentsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1180, 730);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exit and Help");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        UserLogin log = new UserLogin(this);
        log.setVisible(true);
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://negrefitnessclub.es/en"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = userTable.getSelectedRow();
        if (selectedRow != -1) {
            int id = (int) userTable.getValueAt(selectedRow, 1); // Assuming the ID is in the second column (index 1)
            cargarIntentTablePU(id);
        }

    }//GEN-LAST:event_userTableMouseClicked

    private void intentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_intentTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = intentTable.getSelectedRow();
    }//GEN-LAST:event_intentTableMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void allIntentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allIntentsButtonActionPerformed
        // TODO add your handling code here:
        cargarIntentTable();
    }//GEN-LAST:event_allIntentsButtonActionPerformed

    private void pendingIntentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendingIntentsButtonActionPerformed
        // TODO add your handling code here:
        cargarPendingIntentTable();
    }//GEN-LAST:event_pendingIntentsButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton allIntentsButton;
    private javax.swing.JTable intentTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logout;
    private javax.swing.JButton pendingIntentsButton;
    private javax.swing.JTable userTable;
    private javax.swing.JPanel videoPanel;
    // End of variables declaration//GEN-END:variables
}
